{
    "swagger":"2.0",
    "info": { 
        "title":"Pristyn",
        "version":"1.0"
    },
    "securityDefinitions":{
        "ApiKeyAuth":{
            "type":"apiKey",
            "in":"header",
            "name": "X-Parse-Rest-Api-Key"
        },
        "appId":{
          "type": "apiKey",
          "in":"header",
          "name": "X-Parse-Application-Id"
        }
      },
    "host": "localhost:1337",
    "basePath":  "/parse/functions",
    "schemes": ["https","http"],
    "produces": [
        "application/json"
      ],
    "paths": {
        "/InsAmount":{
            "post": {
                "description": "Dashboard_Description",
                "security": [{
                  "ApiKeyAuth":[],
                  "appId":[]
                }],
                "parameters": [
                    {
                      "name": "InsStatus",
                      "in":"formData",
                      "description": "Status of Insurance",
                      "required": true,
                      "type":"string"
                    },{
                      "name": "PaymentMode",
                      "in":"formData",
                      "description": "Type of payment",
                      "required": true,
                      "type":"string"
                    }
                  ],                
                  "tags": [
                    "Insurance"
                  ],
                  "responses": {
                    "200": {
                      "description": "Contains an array",
                      "schema":{
                        "$ref": "#/definitions/Result"
                      }
                    },
                    "default": {
                      "description": "Unexpected error",
                      "schema":{
                        "$ref":"#/definitions/Error"
                      }
                    }
                  }
                }
              }
            },
              
            "definitions": {
              "Result" :{
                "properties": {
                  "result":{
                    "type":"object",
                    "properties": {
                      "message":{
                        "type":"string"
                      },
                      "status":{
                        "type":"number"
                      },
                      "data":{
                        "type":"array",
                        "items": {}
                      }
    
                    }
                  }
                }
               },
               "Error":{
                 "properties": {
                   "message":{
                     "type":"string"
                   }
                 }
               }
              }
            
          }


  
        
  
